Test `@mel.as` in inline record

  $ . ./setup.sh
  $ cat > x.ml <<EOF
  > type t = User of { name : string [@mel.as "author"] }
  > let user = User { name = "my name" }
  $ melc -ppx melppx x.ml
  // Generated by Melange
  'use strict';
  
  
  var user = /* User */{
    author: "my name"
  };
  
  exports.user = user;
  /* No side effect */
